/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    services: Service;
    'service-areas': ServiceArea;
    faqs: Faq;
    reviews: Review;
    projects: Project;
    leads: Lead;
    offers: Offer;
    'paid-landing-pages': PaidLandingPage;
    'lead-magnets': LeadMagnet;
    'blog-posts': BlogPost;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'service-areas': ServiceAreasSelect<false> | ServiceAreasSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    'paid-landing-pages': PaidLandingPagesSelect<false> | PaidLandingPagesSelect<true>;
    'lead-magnets': LeadMagnetsSelect<false> | LeadMagnetsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  tagline: string;
  primaryValuePillar: 'financial' | 'safety' | 'transformation';
  supportingPillars?: ('financial' | 'safety' | 'transformation')[] | null;
  /**
   * Core services are primary offerings. Specialized services are complementary.
   */
  serviceType?: ('core' | 'specialized') | null;
  heroImage: number | Media;
  overview: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  process?:
    | {
        stepTitle: string;
        stepDescription: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        stepImage?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  anxietyStack?: {
    structuralSafety?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    codeCompliance?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    drainageMoisture?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    dustDisruption?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    costAffordability?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    aesthetics?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    timeline?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  differentiator?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faqs?: (number | Faq)[] | null;
  projects?: (number | Project)[] | null;
  reviews?: (number | Review)[] | null;
  ctaHeadline?: string | null;
  seo: {
    metaTitle: string;
    metaDescription: string;
    ogImage?: (number | null) | Media;
  };
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category:
    | 'cost'
    | 'code-compliance'
    | 'city-variability'
    | 'timeline'
    | 'disruption'
    | 'financing-rebates'
    | 'drainage-moisture'
    | 'rental-readiness'
    | 'general';
  applicableServices?: (number | Service)[] | null;
  applicableAreas?: (number | ServiceArea)[] | null;
  sortOrder?: number | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Geographic markets BaseScape serves. Each generates a unique location page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-areas".
 */
export interface ServiceArea {
  id: number;
  cityName: string;
  stateAbbrev: string;
  slug: string;
  county: 'utah' | 'salt-lake' | 'davis';
  coordinates: {
    lat: number;
    lng: number;
  };
  /**
   * Service radius in miles
   */
  serviceRadius: number;
  /**
   * Unique localized copy — not template-swapped
   */
  localContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Genuine local references (landmarks, neighborhoods, concerns)
   */
  localReferences: string;
  localProjects?: (number | Project)[] | null;
  localReviews?: (number | Review)[] | null;
  localFAQs?: (number | Faq)[] | null;
  heroImage?: (number | null) | Media;
  seo: {
    metaTitle: string;
    metaDescription: string;
  };
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  projectType: number | Service;
  city: number | ServiceArea;
  challenge: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  solution: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  outcome: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  beforeImages: {
    image: number | Media;
    caption?: string | null;
    id?: string | null;
  }[];
  afterImages: {
    image: number | Media;
    caption?: string | null;
    id?: string | null;
  }[];
  detailImages?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  reviewerName: string;
  reviewText: string;
  starRating: number;
  city?: (number | null) | ServiceArea;
  serviceType?: (number | null) | Service;
  source: string;
  reviewDate?: string | null;
  featured?: boolean | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Submitted prospect records from website forms.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  /**
   * Client-generated UUID linking partial form steps
   */
  sessionId: string;
  status: 'partial' | 'complete' | 'abandoned' | 'contacted' | 'qualified';
  currentStep: number;
  serviceType?:
    | (
        | 'walkout-basement'
        | 'basement-remodeling'
        | 'pavers-hardscapes'
        | 'retaining-walls'
        | 'artificial-turf'
        | 'egress-window'
        | 'not-sure'
      )
    | null;
  zipCode?: string | null;
  projectPurpose?: ('rental-unit' | 'family-space' | 'home-office' | 'safety-compliance' | 'other') | null;
  timeline?: ('asap' | '1-3-months' | '3-6-months' | '6-plus-months' | 'just-researching') | null;
  name?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  additionalNotes?: string | null;
  source: {
    page: string;
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    utmContent?: string | null;
    utmTerm?: string | null;
    referrer?: string | null;
  };
  isOutOfServiceArea?: boolean | null;
  formType: 'multi-step' | 'quick-callback' | 'lead-magnet';
  confirmationSentAt?: string | null;
  teamNotifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Time-bound or evergreen promotions displayed on pages and landing pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  headline: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Offer terms and conditions
   */
  terms?: string | null;
  startDate: string;
  /**
   * Leave empty for evergreen offers
   */
  endDate?: string | null;
  applicableServices?: (number | Service)[] | null;
  applicablePages?: ('homepage' | 'service' | 'location' | 'landing-page')[] | null;
  status: 'draft' | 'active' | 'expired';
  updatedAt: string;
  createdAt: string;
}
/**
 * Campaign-specific conversion pages with suppressed navigation.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paid-landing-pages".
 */
export interface PaidLandingPage {
  id: number;
  /**
   * URL path under /lp/ (e.g., "walkout-spring-2026")
   */
  campaignSlug: string;
  /**
   * Aligned with ad copy
   */
  headline: string;
  subheadline?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Focused offer content
   */
  bodyContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  trustBadges: ('licensed' | 'insured' | 'bonded' | 'free-estimate' | 'no-hidden-charges' | 'dust-containment')[];
  formType: 'multi-step' | 'quick-callback';
  offer?: (number | null) | Offer;
  /**
   * Pre-selects service on the embedded form
   */
  targetService?: (number | null) | Service;
  /**
   * Suppress standard header/footer navigation (FR-041)
   */
  suppressNavigation?: boolean | null;
  /**
   * Expected campaign tag for analytics matching
   */
  utmCampaign?: string | null;
  seo: {
    metaTitle: string;
    metaDescription: string;
    /**
     * Landing pages are typically noindex
     */
    noindex?: boolean | null;
  };
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Gated educational resources (e.g., "Utah ADU Compliance Checklist").
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-magnets".
 */
export interface LeadMagnet {
  id: number;
  title: string;
  slug: string;
  /**
   * What the resource covers
   */
  description: string;
  /**
   * Downloadable file (PDF)
   */
  file: number | Media;
  /**
   * Preview image for CTA
   */
  thumbnailImage?: (number | null) | Media;
  ctaText: string;
  requiredFields: ('name' | 'email' | 'phone')[];
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Educational content for organic SEO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  heroImage?: (number | null) | Media;
  /**
   * Article content with embedded CTAs
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category:
    | 'walkout-basements'
    | 'egress-windows'
    | 'basement-remodeling'
    | 'retaining-walls'
    | 'adu-compliance'
    | 'financing'
    | 'local-guides'
    | 'safety';
  relatedServices?: (number | Service)[] | null;
  /**
   * Embedded lead magnet CTA (FR-040)
   */
  leadMagnetCTA?: (number | null) | LeadMagnet;
  author: string;
  publishDate: string;
  seo: {
    metaTitle: string;
    metaDescription: string;
  };
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'service-areas';
        value: number | ServiceArea;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'paid-landing-pages';
        value: number | PaidLandingPage;
      } | null)
    | ({
        relationTo: 'lead-magnets';
        value: number | LeadMagnet;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tagline?: T;
  primaryValuePillar?: T;
  supportingPillars?: T;
  serviceType?: T;
  heroImage?: T;
  overview?: T;
  process?:
    | T
    | {
        stepTitle?: T;
        stepDescription?: T;
        stepImage?: T;
        id?: T;
      };
  anxietyStack?:
    | T
    | {
        structuralSafety?: T;
        codeCompliance?: T;
        drainageMoisture?: T;
        dustDisruption?: T;
        costAffordability?: T;
        aesthetics?: T;
        timeline?: T;
      };
  differentiator?: T;
  faqs?: T;
  projects?: T;
  reviews?: T;
  ctaHeadline?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-areas_select".
 */
export interface ServiceAreasSelect<T extends boolean = true> {
  cityName?: T;
  stateAbbrev?: T;
  slug?: T;
  county?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  serviceRadius?: T;
  localContent?: T;
  localReferences?: T;
  localProjects?: T;
  localReviews?: T;
  localFAQs?: T;
  heroImage?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  applicableServices?: T;
  applicableAreas?: T;
  sortOrder?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  reviewerName?: T;
  reviewText?: T;
  starRating?: T;
  city?: T;
  serviceType?: T;
  source?: T;
  reviewDate?: T;
  featured?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  projectType?: T;
  city?: T;
  challenge?: T;
  solution?: T;
  outcome?: T;
  beforeImages?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  afterImages?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  detailImages?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  featured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  sessionId?: T;
  status?: T;
  currentStep?: T;
  serviceType?: T;
  zipCode?: T;
  projectPurpose?: T;
  timeline?: T;
  name?: T;
  phone?: T;
  email?: T;
  address?: T;
  additionalNotes?: T;
  source?:
    | T
    | {
        page?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        utmContent?: T;
        utmTerm?: T;
        referrer?: T;
      };
  isOutOfServiceArea?: T;
  formType?: T;
  confirmationSentAt?: T;
  teamNotifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  headline?: T;
  description?: T;
  terms?: T;
  startDate?: T;
  endDate?: T;
  applicableServices?: T;
  applicablePages?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paid-landing-pages_select".
 */
export interface PaidLandingPagesSelect<T extends boolean = true> {
  campaignSlug?: T;
  headline?: T;
  subheadline?: T;
  heroImage?: T;
  bodyContent?: T;
  trustBadges?: T;
  formType?: T;
  offer?: T;
  targetService?: T;
  suppressNavigation?: T;
  utmCampaign?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        noindex?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-magnets_select".
 */
export interface LeadMagnetsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  file?: T;
  thumbnailImage?: T;
  ctaText?: T;
  requiredFields?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  category?: T;
  relatedServices?: T;
  leadMagnetCTA?: T;
  author?: T;
  publishDate?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  businessName: string;
  phone: string;
  email: string;
  address: {
    street: string;
    city: string;
    state: string;
    zip: string;
  };
  operatingHours?:
    | {
        day: 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday';
        open: string;
        close: string;
        id?: string | null;
      }[]
    | null;
  licenseNumber?: string | null;
  insuranceInfo?: string | null;
  socialLinks?: {
    google?: string | null;
    facebook?: string | null;
    instagram?: string | null;
  };
  /**
   * Show "What Homeowners Say" sections site-wide
   */
  showReviews?: boolean | null;
  /**
   * Show Gallery page and navigation links
   */
  showGallery?: boolean | null;
  riskReversals?:
    | {
        statement: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Newline-separated list of valid zip codes in the service area.
   */
  serviceAreaZipCodes?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  mainNav?:
    | {
        label: string;
        url: string;
        children?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerNav?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  businessName?: T;
  phone?: T;
  email?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  operatingHours?:
    | T
    | {
        day?: T;
        open?: T;
        close?: T;
        id?: T;
      };
  licenseNumber?: T;
  insuranceInfo?: T;
  socialLinks?:
    | T
    | {
        google?: T;
        facebook?: T;
        instagram?: T;
      };
  showReviews?: T;
  showGallery?: T;
  riskReversals?:
    | T
    | {
        statement?: T;
        id?: T;
      };
  serviceAreaZipCodes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainNav?:
    | T
    | {
        label?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  footerNav?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}